"""Normalize country names to a consistent English display form."""

from __future__ import annotations

import re

COUNTRY_ALIASES: dict[str, str] = {
    "afghanistan": "Afghanistan",
    "albania": "Albania",
    "algeria": "Algeria",
    "andorra": "Andorra",
    "angola": "Angola",
    "argentina": "Argentina",
    "armenia": "Armenia",
    "australia": "Australia",
    "austria": "Austria",
    "österreich": "Austria",
    "azerbaijan": "Azerbaijan",
    "bahrain": "Bahrain",
    "bangladesh": "Bangladesh",
    "belarus": "Belarus",
    "belgium": "Belgium",
    "belgië": "Belgium",
    "belgie": "Belgium",
    "belgique": "Belgium",
    "be": "Belgium",
    "bolivia": "Bolivia",
    "bosnia and herzegovina": "Bosnia and Herzegovina",
    "bosnia": "Bosnia and Herzegovina",
    "brazil": "Brazil",
    "brasil": "Brazil",
    "br": "Brazil",
    "bulgaria": "Bulgaria",
    "cambodia": "Cambodia",
    "cameroon": "Cameroon",
    "canada": "Canada",
    "ca": "Canada",
    "chile": "Chile",
    "china": "China",
    "cn": "China",
    "colombia": "Colombia",
    "costa rica": "Costa Rica",
    "croatia": "Croatia",
    "hrvatska": "Croatia",
    "cuba": "Cuba",
    "cyprus": "Cyprus",
    "czech republic": "Czech Republic",
    "czechia": "Czech Republic",
    "denmark": "Denmark",
    "danmark": "Denmark",
    "dk": "Denmark",
    "dominican republic": "Dominican Republic",
    "ecuador": "Ecuador",
    "egypt": "Egypt",
    "el salvador": "El Salvador",
    "estonia": "Estonia",
    "ethiopia": "Ethiopia",
    "finland": "Finland",
    "suomi": "Finland",
    "fi": "Finland",
    "france": "France",
    "fr": "France",
    "georgia": "Georgia",
    "germany": "Germany",
    "deutschland": "Germany",
    "de": "Germany",
    "ghana": "Ghana",
    "greece": "Greece",
    "guatemala": "Guatemala",
    "honduras": "Honduras",
    "hong kong": "Hong Kong",
    "hungary": "Hungary",
    "iceland": "Iceland",
    "india": "India",
    "in": "India",
    "indonesia": "Indonesia",
    "iran": "Iran",
    "iraq": "Iraq",
    "ireland": "Ireland",
    "ie": "Ireland",
    "israel": "Israel",
    "italy": "Italy",
    "italia": "Italy",
    "it": "Italy",
    "jamaica": "Jamaica",
    "japan": "Japan",
    "jp": "Japan",
    "jordan": "Jordan",
    "kazakhstan": "Kazakhstan",
    "kenya": "Kenya",
    "kuwait": "Kuwait",
    "latvia": "Latvia",
    "lebanon": "Lebanon",
    "libya": "Libya",
    "liechtenstein": "Liechtenstein",
    "lithuania": "Lithuania",
    "luxembourg": "Luxembourg",
    "luxemburg": "Luxembourg",
    "macau": "Macau",
    "macao": "Macau",
    "malaysia": "Malaysia",
    "malta": "Malta",
    "mexico": "Mexico",
    "méxico": "Mexico",
    "mx": "Mexico",
    "moldova": "Moldova",
    "monaco": "Monaco",
    "mongolia": "Mongolia",
    "montenegro": "Montenegro",
    "morocco": "Morocco",
    "mozambique": "Mozambique",
    "myanmar": "Myanmar",
    "nepal": "Nepal",
    "netherlands": "Netherlands",
    "the netherlands": "Netherlands",
    "holland": "Netherlands",
    "nederland": "Netherlands",
    "nl": "Netherlands",
    "new zealand": "New Zealand",
    "nicaragua": "Nicaragua",
    "nigeria": "Nigeria",
    "north macedonia": "North Macedonia",
    "macedonia": "North Macedonia",
    "norway": "Norway",
    "norge": "Norway",
    "no": "Norway",
    "oman": "Oman",
    "pakistan": "Pakistan",
    "panama": "Panama",
    "paraguay": "Paraguay",
    "peru": "Peru",
    "philippines": "Philippines",
    "poland": "Poland",
    "polska": "Poland",
    "pl": "Poland",
    "portugal": "Portugal",
    "pt": "Portugal",
    "puerto rico": "Puerto Rico",
    "qatar": "Qatar",
    "romania": "Romania",
    "russia": "Russia",
    "russian federation": "Russia",
    "saudi arabia": "Saudi Arabia",
    "uae": "United Arab Emirates",
    "united arab emirates": "United Arab Emirates",
    "senegal": "Senegal",
    "serbia": "Serbia",
    "singapore": "Singapore",
    "sg": "Singapore",
    "slovakia": "Slovakia",
    "slovenia": "Slovenia",
    "south africa": "South Africa",
    "south korea": "South Korea",
    "korea": "South Korea",
    "republic of korea": "South Korea",
    "kr": "South Korea",
    "spain": "Spain",
    "españa": "Spain",
    "espana": "Spain",
    "es": "Spain",
    "sri lanka": "Sri Lanka",
    "sudan": "Sudan",
    "sweden": "Sweden",
    "sverige": "Sweden",
    "se": "Sweden",
    "switzerland": "Switzerland",
    "schweiz": "Switzerland",
    "suisse": "Switzerland",
    "ch": "Switzerland",
    "syria": "Syria",
    "taiwan": "Taiwan",
    "tanzania": "Tanzania",
    "thailand": "Thailand",
    "tunisia": "Tunisia",
    "turkey": "Turkey",
    "türkiye": "Turkey",
    "turkiye": "Turkey",
    "tr": "Turkey",
    "uganda": "Uganda",
    "ukraine": "Ukraine",
    "united kingdom": "United Kingdom",
    "uk": "United Kingdom",
    "gb": "United Kingdom",
    "great britain": "United Kingdom",
    "england": "United Kingdom",
    "united states": "United States",
    "united states of america": "United States",
    "usa": "United States",
    "us": "United States",
    "u.s.": "United States",
    "u.s.a.": "United States",
    "america": "United States",
    "uruguay": "Uruguay",
    "uzbekistan": "Uzbekistan",
    "venezuela": "Venezuela",
    "vietnam": "Vietnam",
    "viet nam": "Vietnam",
    "yemen": "Yemen",
    "zambia": "Zambia",
    "zimbabwe": "Zimbabwe",
}

_SMALL_WORDS = frozenset({"and", "of", "the"})


def _lookup_key(value: str) -> str:
    key = value.strip().lower()
    key = re.sub(r"\s+", " ", key)
    if key.startswith("the "):
        key = key[4:]
    return key


def normalize_country(value: str | None) -> str | None:
    if value is None:
        return None
    raw = str(value).strip()
    if not raw:
        return None
    key = _lookup_key(raw)
    if key in COUNTRY_ALIASES:
        return COUNTRY_ALIASES[key]
    words = key.split()
    titled = []
    for idx, word in enumerate(words):
        if idx > 0 and word in _SMALL_WORDS:
            titled.append(word)
        else:
            titled.append(word.capitalize())
    return " ".join(titled)
